"""add fields for pda and status in AIModel

Revision ID: 5999d633eadc
Revises: 
Create Date: 2025-10-14 12:59:16.508554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5999d633eadc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_databases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_uri', sa.String(length=1024), nullable=False))
        batch_op.add_column(sa.Column('data_hash', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('merkle_root', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_databases_data_hash'), ['data_hash'], unique=False)
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_hash')

    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_pda', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.drop_column('last_error')
        batch_op.drop_column('status')
        batch_op.drop_column('model_pda')

    with op.batch_alter_table('ai_databases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_index(batch_op.f('ix_ai_databases_data_hash'))
        batch_op.drop_column('merkle_root')
        batch_op.drop_column('data_hash')
        batch_op.drop_column('storage_uri')

    # ### end Alembic commands ###
